name: Go Module Release

on:
  workflow_dispatch:  # 手动触发
    inputs:
      version:
        description: "Enter the release version (e.g., v0.1.1)"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24'
      - name: Build and Test
        run: |
          cd golang
          go mod download
      - name: Publish to Go Module
        run: |
          VERSION=${{ inputs.version }}
          cd golang
          git tag -d $VERSION || true
          git push origin :refs/tags/$VERSION || true
          git tag -a $VERSION -m "Release $VERSION"
          git push origin $VERSION
